/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.72
 * Generated at: 2023-05-30 07:12:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class project_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

    String ctxPath = request.getContextPath();

      out.write("     \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	body {\r\n");
      out.write("		word-break: break-all; /* 공백없이 영어로만 되어질 경우 해당구역을 뚫고 빠져나감으로 이것을 막기 위해서 사용한다 */\r\n");
      out.write("		padding: 0;            /* 상 우 하 좌 모두 안쪽여백을 0px을 준 것이다. 즉, 바깥여백을 없는 것으로 한 것이다.*/\r\n");
      out.write("	}	\r\n");
      out.write("\r\n");
      out.write("	div#container{\r\n");
      out.write("		width: 70%;\r\n");
      out.write("		margin: 0px auto 20px auto; /* 상 하는 20px 우 좌는 남은 20%에서 좌우로 균등하게 주겠다. 즉, 화면의 가운데로 위치하겠다는 말이다.*/\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div#left{\r\n");
      out.write("		 float: left;\r\n");
      out.write("		 width: 15%;\r\n");
      out.write("		 height: 420px; \r\n");
      out.write("		 background-color: white; \r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write("	div#middle {\r\n");
      out.write("		 float: left;\r\n");
      out.write("		 background-repeat: no-repeat;\r\n");
      out.write("		 background-size:cover;  \r\n");
      out.write("		 background-position: center center; \r\n");
      out.write("		 height: 400px;\r\n");
      out.write("  	     width: 70%; \r\n");
      out.write("  	     background-blend-mode: multiply;\r\n");
      out.write("  	     border-radius: 10px 10px;\r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	div#right{\r\n");
      out.write("		 float: left;\r\n");
      out.write("		 width: 15%;\r\n");
      out.write("		 height: 420px; \r\n");
      out.write("		 background-color: white;\r\n");
      out.write("		 \r\n");
      out.write("	}  \r\n");
      out.write("\r\n");
      out.write("	div#poster{\r\n");
      out.write("	    float: left;\r\n");
      out.write("		border: solid 1px #b3b3b3;\r\n");
      out.write("		width: 23%;\r\n");
      out.write("		height: 400px;\r\n");
      out.write("		border-radius: 10px 10px;\r\n");
      out.write("		background-repeat: no-repeat;\r\n");
      out.write("		background-size:cover;  \r\n");
      out.write("	}	\r\n");
      out.write("	  \r\n");
      out.write("	div#posterInfo{\r\n");
      out.write("	    float: left;\r\n");
      out.write("		border: solid 1px #b3b3b3;\r\n");
      out.write("		width: 75%;\r\n");
      out.write("		height: 400px; \r\n");
      out.write("		margin: 0px 0px 20px 20px; \r\n");
      out.write("		border-radius: 10px 10px;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	div#BasicInfo{\r\n");
      out.write("		border: solid 1.5px #b3b3b3;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		height: 600px;\r\n");
      out.write("		border-radius: 10px 10px;\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("	div#cast{\r\n");
      out.write("		border: solid 1.5px #b3b3b3;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		height: 470px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		border-radius: 10px 10px;	\r\n");
      out.write("	}	 \r\n");
      out.write("	\r\n");
      out.write("	div#Comment{\r\n");
      out.write("		border: solid 1.5px #b3b3b3;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		height: 600px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		border-radius: 10px 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div#Video{\r\n");
      out.write("		border: solid 1.5px #b3b3b3;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		height: 600px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		border-radius: 10px 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div#img_8{\r\n");
      out.write("		border: solid 1.5px #b3b3b3;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("		height: 800px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		border-radius: 10px 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/*평가하기 시작*/\r\n");
      out.write("	.rate { display: inline-block;border: 0; margin-right: 15px;}\r\n");
      out.write("	.rate > input {display: none;}\r\n");
      out.write("	.rate > label {float: right;color: #ddd}\r\n");
      out.write("	.rate > label:before {display: inline-block;font-size: 2rem;padding: .3rem .2rem;margin: 0;cursor: pointer;font-family: FontAwesome;content: \"\\f005 \";}\r\n");
      out.write("	.rate .half:before {content: \"\\f089 \"; position: absolute;padding-right: 0;}\r\n");
      out.write("	.rate input:checked ~ label, \r\n");
      out.write("	.rate label:hover,.rate label:hover ~ label { color: #FDD346} \r\n");
      out.write("	.rate input:checked + .rate label:hover,\r\n");
      out.write("	.rate input input:checked ~ label:hover,\r\n");
      out.write("	.rate input:checked ~ .rate label:hover ~ label,  \r\n");
      out.write("	.rate label:hover ~ input:checked ~ label { color: #FDD346} \r\n");
      out.write("	/*평가하기 끝*/\r\n");
      out.write("	\r\n");
      out.write("	/* 출연,제작 시작 */ \r\n");
      out.write("	@media (max-width: 768px) {\r\n");
      out.write("	    .carousel-inner .carousel-item > div {\r\n");
      out.write("	        display: none;\r\n");
      out.write("	    }\r\n");
      out.write("	    .carousel-inner .carousel-item > div:first-child {\r\n");
      out.write("	        display: block;\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.carousel-inner .carousel-item.active,\r\n");
      out.write("	.carousel-inner .carousel-item-next,\r\n");
      out.write("	.carousel-inner .carousel-item-prev {\r\n");
      out.write("	    display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* display 3 */\r\n");
      out.write("	@media (min-width: 768px) {\r\n");
      out.write("	    \r\n");
      out.write("	    .carousel-inner .carousel-item-right.active,\r\n");
      out.write("	    .carousel-inner .carousel-item-next {\r\n");
      out.write("	      transform: translateX(33.333%);\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    .carousel-inner .carousel-item-left.active, \r\n");
      out.write("	    .carousel-inner .carousel-item-prev {\r\n");
      out.write("	      transform: translateX(-33.333%);\r\n");
      out.write("	    }\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.carousel-inner .carousel-item-right,\r\n");
      out.write("	.carousel-inner .carousel-item-left{ \r\n");
      out.write("	  transform: translateX(0);\r\n");
      out.write("	}\r\n");
      out.write("	/* 출연,제작 끝 */\r\n");
      out.write("	\r\n");
      out.write("     /* 사진 시작 */	 \r\n");
      out.write(" 	div#carousel3D { \r\n");
      out.write("	  perspective: 1200px;  \r\n");
      out.write("	  background: white; \r\n");
      out.write("	  padding-top: 4%;  \r\n");
      out.write("	  font-size:0; \r\n");
      out.write("	  margin-bottom: 3rem; \r\n");
      out.write("	  overflow: hidden; \r\n");
      out.write("	}\r\n");
      out.write("	figure#spinner3D { \r\n");
      out.write("	  transform-style: preserve-3d; \r\n");
      out.write("	  height: 600px; \r\n");
      out.write("	  transform-origin: 50% 50% -500px; \r\n");
      out.write("	  transition: 1s; \r\n");
      out.write("	} \r\n");
      out.write("	figure#spinner3D img { \r\n");
      out.write("	  width: 40%; max-width: 400px;  \r\n");
      out.write("	  position: absolute; left: 30%;\r\n");
      out.write("	  transform-origin: 50% 50% -500px;\r\n");
      out.write("	  outline:1px solid transparent; \r\n");
      out.write("	}\r\n");
      out.write("	figure#spinner3D img:nth-child(1) { transform:rotateY(0deg); \r\n");
      out.write("	}\r\n");
      out.write("	figure#spinner3D img:nth-child(2) { transform: rotateY(-45deg); }\r\n");
      out.write("	figure#spinner3D img:nth-child(3) { transform: rotateY(-90deg); }\r\n");
      out.write("	figure#spinner3D img:nth-child(4) { transform: rotateY(-135deg); }\r\n");
      out.write("	figure#spinner3D img:nth-child(5){ transform: rotateY(-180deg); }\r\n");
      out.write("	figure#spinner3D img:nth-child(6){ transform: rotateY(-225deg); }\r\n");
      out.write("	figure#spinner3D img:nth-child(7){ transform: rotateY(-270deg); }\r\n");
      out.write("	figure#spinner3D img:nth-child(8){ transform: rotateY(-315deg); }\r\n");
      out.write("	div#carousel3D ~ span { \r\n");
      out.write("	  color: black; \r\n");
      out.write("	  margin: 5%; \r\n");
      out.write("	  display: inline-block; \r\n");
      out.write("	  text-decoration: none; \r\n");
      out.write("	  font-size: 3rem; \r\n");
      out.write("	  transition: 0.6s color; \r\n");
      out.write("	  position: relative; \r\n");
      out.write("	  margin-top: -6rem;  \r\n");
      out.write("	  border-bottom: none; \r\n");
      out.write("	  line-height: 0; \r\n");
      out.write("	  bottom: 350px;\r\n");
      out.write("	  }\r\n");
      out.write("	div#carousel3D ~ span:hover { color: #888; cursor: pointer; } \r\n");
      out.write("	/* 사진 끝 */	\r\n");
      out.write("	\r\n");
      out.write("	/*보고싶어요 시작*/\r\n");
      out.write("	input[type=\"checkbox\"] { \r\n");
      out.write("	   opacity: 0;\r\n");
      out.write("	}\r\n");
      out.write("    /*보고싶어요 끝*/\r\n");
      out.write("	\r\n");
      out.write("	/*코멘트 시작*/\r\n");
      out.write("	div#registerComment{font-family: 'Noto Sans KR', sans-serif;}\r\n");
      out.write("	.modal-body textarea:focus,\r\n");
      out.write("	.modal-body input:focus {outline: none;}\r\n");
      out.write("	.fa-face-meh:hover{color: #ff0558; cursor: pointer;}\r\n");
      out.write("	/*코멘트 끝*/\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	/* 출연, 제작 시작*/\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		$('#recipeCarousel').carousel({ \r\n");
      out.write("			  interval: 10000\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	$('.carousel .carousel-item').each(function(){\r\n");
      out.write("	    var minPerSlide = 7;\r\n");
      out.write("	    var next = $(this).next();\r\n");
      out.write("	    if (!next.length) {\r\n");
      out.write("	        next = $(this).siblings(':first');\r\n");
      out.write("	    }\r\n");
      out.write("	    next.children(':first-child').clone().appendTo($(this));\r\n");
      out.write("	    \r\n");
      out.write("	    for (var i=0;i<minPerSlide;i++) {\r\n");
      out.write("	        next=next.next();\r\n");
      out.write("	        if (!next.length) {\r\n");
      out.write("	        	next = $(this).siblings(':first');\r\n");
      out.write("	      	}\r\n");
      out.write("	        \r\n");
      out.write("	        next.children(':first-child').clone().appendTo($(this));\r\n");
      out.write("	   }\r\n");
      out.write("	});\r\n");
      out.write("	/* 출연, 제작 끝*/\r\n");
      out.write("	\r\n");
      out.write("	/*보고싶어요 시작*/	\r\n");
      out.write("	$(\".seechange2\").hide(); \r\n");
      out.write("	\r\n");
      out.write("	$(\"input:checkbox[name='check_wantsee']\").click(function(){\r\n");
      out.write("		 \r\n");
      out.write("		if($('input:checkbox[name=\"check_wantsee\"]').is(\":checked\")) {\r\n");
      out.write("				$(\".seechange1\").hide(); \r\n");
      out.write("				$(\".seechange2\").show(); \r\n");
      out.write("				$(\".seechange2\").css({\"color\":\"#f3578d\"}); \r\n");
      out.write("			 	$(\".wantseei\").css({\"color\":\"#f3578d\"}); \r\n");
      out.write("			}\r\n");
      out.write("			else if(!$('input:checkbox[name=\"check_wantsee\"]').is(\":checked\")) {\r\n");
      out.write("				$(\".seechange1\").show(); \r\n");
      out.write("				$(\".seechange2\").hide(); \r\n");
      out.write("				$(\".wantseei\").css({\"color\":\"\"}); \r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			$(\"input:checkbox[name='check_wantsee']\").toggle();\r\n");
      out.write("		\r\n");
      out.write("	  });\r\n");
      out.write("	/*보고싶어요 끝*/		\r\n");
      out.write("\r\n");
      out.write("	/*코멘트 시작*/		\r\n");
      out.write("	$(\"input:checkbox[name='check_comment']\").click(function(){\r\n");
      out.write("		\r\n");
      out.write("		if($('input:checkbox[name=\"check_comment\"]').is(\":checked\")) {\r\n");
      out.write("			 \r\n");
      out.write("		 	$(\".commenti\").css({\"color\":\"#f3578d\"}); \r\n");
      out.write("		}\r\n");
      out.write("		else if(!$('input:checkbox[name=\"check_comment\"]').is(\":checked\")) {\r\n");
      out.write("\r\n");
      out.write("			$(\".commenti\").css({\"background-color\":\"\",\"color\":\"\"}); \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\"input:checkbox[name='check_comment']\").toggle();\r\n");
      out.write("		\r\n");
      out.write("	  });\r\n");
      out.write("	/*코멘트 끝*/\r\n");
      out.write("	\r\n");
      out.write("	/*보는중 시작*/		\r\n");
      out.write("	$(\"input:checkbox[name='check_seeing']\").click(function(){\r\n");
      out.write("		  \r\n");
      out.write("		if($('input:checkbox[name=\"check_seeing\"]').is(\":checked\")) {\r\n");
      out.write("			 \r\n");
      out.write("		 	$(\".seeingi\").css({\"color\":\"#f3578d\"}); \r\n");
      out.write("		}\r\n");
      out.write("		else if(!$('input:checkbox[name=\"check_seeing\"]').is(\":checked\")) {\r\n");
      out.write("\r\n");
      out.write("			$(\".seeingi\").css({\"background-color\":\"\",\"color\":\"\"}); \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\"input:checkbox[name='check_seeing']\").toggle();\r\n");
      out.write("		\r\n");
      out.write("	  });\r\n");
      out.write("	/*보는중 끝*/\r\n");
      out.write("	\r\n");
      out.write("	/* 영화 등 정보 불러오기 시작 */\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"");
      out.print( ctxPath);
      out.write("/movieInfo.action\",\r\n");
      out.write("		dataType:\"json\",\r\n");
      out.write("		success:function(json){\r\n");
      out.write("			\r\n");
      out.write("			//console.log(JSON.stringify(json));\r\n");
      out.write("			console.log(json);\r\n");
      out.write("		},\r\n");
      out.write("		error: function(request, status, error){\r\n");
      out.write("                 alert(\"code: \"+request.status+\"\\n\"+\"message: \"+request.responseText+\"\\n\"+\"error: \"+error);\r\n");
      out.write("           }\r\n");
      out.write("	});\r\n");
      out.write("	/* 영화 등 정보 불러오기 끝 */\r\n");
      out.write("	\r\n");
      out.write("	});//end of $(document).ready(function())----------------------------------------------------------------------------------\r\n");
      out.write("	\r\n");
      out.write("	/* 사진 시작*/\r\n");
      out.write("	var angle = 0;\r\n");
      out.write("	\r\n");
      out.write("	function galleryspin(sign) { \r\n");
      out.write("	spinner3D = document.querySelector(\"#spinner3D\");\r\n");
      out.write("	if (!sign) { angle = angle + 45; } else { angle = angle - 45; }\r\n");
      out.write("	spinner3D.setAttribute(\"style\",\"-webkit-transform: rotateY(\"+ angle +\"deg); -moz-transform: rotateY(\"+ angle +\"deg); transform: rotateY(\"+ angle +\"deg);\");\r\n");
      out.write("	}\r\n");
      out.write("	/*사진  끝*/\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>제품상세</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<div id=\"left\"></div>\r\n");
      out.write("		 \r\n");
      out.write("		<div id=\"middle\" style=\"background: url('https://image.tmdb.org/t/p/w1280/5DKVH8KeqFwPacWFMyYqTaECxJP.jpg')\"></div> \r\n");
      out.write("		  \r\n");
      out.write("		<div id=\"right\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		 \r\n");
      out.write("		<div id=\"poster\" style=\"background-image: url('https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg');\"></div>\r\n");
      out.write("	\r\n");
      out.write("		<div id=\"posterInfo\"> \r\n");
      out.write("			<div style=\"margin: 30px 0 0 30px;\">\r\n");
      out.write("				<div style=\"margin: 0 0 20px 0; font-size: 40px; font-weight: bolder;\">범죄도시3</div>\r\n");
      out.write("				\r\n");
      out.write("				<div style=\"font-weight: bold;\">2023&nbsp;&nbsp;<span style=\"color: #eee;\">|</span>&nbsp;&nbsp;범죄&nbsp;&nbsp;<span style=\"color: #eee;\">|</span>&nbsp;&nbsp;한국</div>\r\n");
      out.write("	\r\n");
      out.write("				<hr style=\"margin-right: 40px;\">	\r\n");
      out.write("	\r\n");
      out.write("				<div style=\"font-weight: bold;\">예매:&nbsp;순위3위(12%)&nbsp;&nbsp;<span style=\"color: #eee;\">|</span>&nbsp;&nbsp;개봉:&nbsp;15일전&nbsp;&nbsp;<span style=\"color: #eee;\">|</span>&nbsp;&nbsp;누적:&nbsp;관객0명</div>\r\n");
      out.write("				\r\n");
      out.write("				<hr style=\"margin-right: 40px;\"> \r\n");
      out.write("				 \r\n");
      out.write("				<div style=\"margin: 50px 0 10px 77px; font-weight: bold;\">평가하기</div> \r\n");
      out.write("				<fieldset class=\"rate\">\r\n");
      out.write("		          <input type=\"radio\" id=\"rating10\" name=\"rating\" value=\"10\"><label for=\"rating10\" title=\"5점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating9\" name=\"rating\" value=\"9\"><label class=\"half\" for=\"rating9\" title=\"4.5점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating8\" name=\"rating\" value=\"8\"><label for=\"rating8\" title=\"4점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating7\" name=\"rating\" value=\"7\"><label class=\"half\" for=\"rating7\" title=\"3.5점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating6\" name=\"rating\" value=\"6\"><label for=\"rating6\" title=\"3점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating5\" name=\"rating\" value=\"5\"><label class=\"half\" for=\"rating5\" title=\"2.5점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating4\" name=\"rating\" value=\"4\"><label for=\"rating4\" title=\"2점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating3\" name=\"rating\" value=\"3\"><label class=\"half\" for=\"rating3\" title=\"1.5점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating2\" name=\"rating\" value=\"2\"><label for=\"rating2\" title=\"1점\"></label>\r\n");
      out.write("		          <input type=\"radio\" id=\"rating1\" name=\"rating\" value=\"1\"><label class=\"half\" for=\"rating1\" title=\"0.5점\"></label>\r\n");
      out.write("		        </fieldset>\r\n");
      out.write("				\r\n");
      out.write("				<div style=\"margin: 0 0 0 270px; position: relative; bottom: 60px;\">  \r\n");
      out.write("					<div>\r\n");
      out.write("						<label for=\"check_wantsee\" style=\"cursor: pointer;\">\r\n");
      out.write("						   <i style=\"font-size: 23px;\" class=\"seechange1 fas fa-plus wantseei\"></i><i style=\"font-size: 23px; margin-right: 3.3px;\" class=\"seechange2 fas fa-bookmark\"></i><span class=\"wantseei\" style=\"font-weight: bolder\">&nbsp;&nbsp;보고싶어요</span>\r\n");
      out.write("						   <input type=\"checkbox\" id=\"check_wantsee\" name=\"check_wantsee\"/>\r\n");
      out.write("						</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("			        <div style=\"position: relative; left: 125px; bottom: 33px;\">\r\n");
      out.write("			          <label for=\"check_comment\" style=\"cursor: pointer;\">\r\n");
      out.write("			             <span class=\"commenti\">\r\n");
      out.write("			               <button type=\"button\" data-toggle=\"modal\" data-target=\"#registerComment\" style=\"font-weight: bold; border: none; background-color: transparent;\">\r\n");
      out.write("			                 <i style=\"font-size: 23px;\" class=\"fas fa-pen-nib commenti\"></i>&nbsp;&nbsp;코멘트 등록\r\n");
      out.write("			               </button>\r\n");
      out.write("			             </span>\r\n");
      out.write("			          </label>\r\n");
      out.write("			        </div> \r\n");
      out.write("					\r\n");
      out.write("					<div style=\"position: relative; left: 275px; bottom: 66px; width: 100px;\"> \r\n");
      out.write("					  <label for=\"check_seeing\" style=\"cursor: pointer;\">\r\n");
      out.write("					    <i style=\"font-size: 23px;\" class=\"far fa-eye seeingi\"></i><span class=\"seeingi\" style=\"font-weight: bolder\">&nbsp;&nbsp;보는중</span></label>\r\n");
      out.write("						<input type=\"checkbox\" id=\"check_seeing\" name=\"check_seeing\"/>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"BasicInfo\">\r\n");
      out.write("		\r\n");
      out.write("			<h4 style=\"margin: 30px 0 20px 30px; font-weight: bolder; \">기본 정보</h4>\r\n");
      out.write("		\r\n");
      out.write("			<ol style=\"margin: 0 0 0 15px; list-style: none;\">   \r\n");
      out.write("		       <li ><span>원제 </span><span style=\"margin-left: 60px;\">범죄도시3</span></li>\r\n");
      out.write("		       <hr style=\"margin-right: 40px;\"> \r\n");
      out.write("		       <li><span>제작 연도 </span><span style=\"margin-left: 27px;\">2023</span></li>\r\n");
      out.write("		       <hr style=\"margin-right: 40px;\"> \r\n");
      out.write("		       <li><span>국가 </span><span style=\"margin-left: 64px;\">한국</span></li>\r\n");
      out.write("		       <hr style=\"margin-right: 40px;\"> \r\n");
      out.write("		       <li><span>장르 </span><span style=\"margin-left: 64px;\">범죄</span></li>\r\n");
      out.write("		       <hr style=\"margin-right: 40px;\"> \r\n");
      out.write("		       <li><span>상영시간 </span><span style=\"margin-left: 35px;\">1시간 45분</span></li>\r\n");
      out.write("		       <hr style=\"margin-right: 40px;\"> \r\n");
      out.write("		       <li><span>연령 등급 </span><span style=\"margin-left: 31px;\">15세 관람가</span></li>\r\n");
      out.write("		       <hr style=\"margin-right: 40px;\">  \r\n");
      out.write("		       <li><div style=\"width: 10%; vertical-align: top; display: inline-block;\">내용 </div>\r\n");
      out.write("			       <div style=\"width: 80%; display: inline-block;\"> \r\n");
      out.write("			                대체불가 괴물형사 마석도, 서울 광수대로 발탁!\r\n");
      out.write("					베트남 납치 살해범 검거 후 7년 뒤, ‘마석도’(마동석)는 새로운 팀원들과 함께 살인사건을 조사한다. 사건 조사 중, ‘마석도’는 신종 마약 사건이 연루되었음을 알게 되고 수사를 확대한다. 한편, 마약 사건의 배후인 '주성철'(이준혁)은 계속해서 판을 키워가고 약을 유통하던 일본 조직과 '리키'(아오키 무네타카)까지 한국에 들어오며 사건의 규모는 점점 더 커져가는데...\r\n");
      out.write("					나쁜 놈들 잡는 데 이유 없고 제한 없다\r\n");
      out.write("					커진 판도 시원하게 싹 쓸어버린다!\r\n");
      out.write("				  </div>\r\n");
      out.write("			  </li>\r\n");
      out.write("		    </ol>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"cast\">\r\n");
      out.write("		\r\n");
      out.write("			<h4 style=\"margin: 30px 0 0 30px; font-weight: bolder; \">출연/제작</h4>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container text-center my-3\">\r\n");
      out.write("			    <div class=\"row mx-auto my-auto\">\r\n");
      out.write("			        <div id=\"recipeCarousel\" class=\"carousel slide w-100\" data-ride=\"carousel\">\r\n");
      out.write("			            <div class=\"carousel-inner w-100\" role=\"listbox\">\r\n");
      out.write("			                <div class=\"carousel-item active\">\r\n");
      out.write("			                    <div class=\"col-md-2\">\r\n");
      out.write("			                        <div class=\"card\">\r\n");
      out.write("									  <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\" class=\"card-img-top\" style=\"width: 100%\" />\r\n");
      out.write("									  <div class=\"card-body\">\r\n");
      out.write("									    <h5 class=\"card-title\">감독</h5>\r\n");
      out.write("									    <p class=\"card-text\">ㅇㅇ</p>\r\n");
      out.write("									    <a href=\"#\" class=\"stretched-link\"></a>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("			                <div class=\"carousel-item\">\r\n");
      out.write("			                    <div class=\"col-md-2\">\r\n");
      out.write("			                        <div class=\"card\">\r\n");
      out.write("									  <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\" class=\"card-img-top\" style=\"width: 100%\" />\r\n");
      out.write("									  <div class=\"card-body\">\r\n");
      out.write("									    <h5 class=\"card-title\">주연</h5>\r\n");
      out.write("									    <p class=\"card-text\">ㅇㅇ</p>\r\n");
      out.write("									    <a href=\"#\" class=\"stretched-link\"></a>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("			                <div class=\"carousel-item\">\r\n");
      out.write("			                    <div class=\"col-md-2\">\r\n");
      out.write("			                        <div class=\"card\">\r\n");
      out.write("									  <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\" class=\"card-img-top\" style=\"width: 100%\" />\r\n");
      out.write("									  <div class=\"card-body\">\r\n");
      out.write("									    <h5 class=\"card-title\">주연</h5>\r\n");
      out.write("									    <p class=\"card-text\">ㅇㅇ</p>\r\n");
      out.write("									    <a href=\"#\" class=\"stretched-link\"></a>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			            <a class=\"carousel-control-prev w-auto\" href=\"#recipeCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("			                <span class=\"carousel-control-prev-icon bg-dark border border-dark rounded-circle\" aria-hidden=\"true\"></span>\r\n");
      out.write("			                <span class=\"sr-only\">Previous</span>\r\n");
      out.write("			            </a>\r\n");
      out.write("			            <a class=\"carousel-control-next w-auto\" href=\"#recipeCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("			                <span class=\"carousel-control-next-icon bg-dark border border-dark rounded-circle\" aria-hidden=\"true\"></span>\r\n");
      out.write("			                <span class=\"sr-only\">Next</span>\r\n");
      out.write("			            </a>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"Comment\">\r\n");
      out.write("		\r\n");
      out.write("			<h4 style=\"margin: 30px 0 0 30px; font-weight: bolder; \">코멘트</h4>\r\n");
      out.write("			  	\r\n");
      out.write("				\r\n");
      out.write("		      ");
      out.write("\r\n");
      out.write("		      <div class=\"modal fade\" id=\"registerComment\">\r\n");
      out.write("		        <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("		          <div class=\"modal-content\">\r\n");
      out.write("		            <div class=\"modal-body\">\r\n");
      out.write("		              <h5 class=\"modal-title\" style=\"font-weight: bold;\">영화제목<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button></h5>\r\n");
      out.write("		               <div class=\"my-2\">\r\n");
      out.write("		                 <textarea style=\"width: 100%; height: 450px; resize: none; border: none;\" placeholder=\"이 작품에 대한 생각을 자유롭게 표현해주세요.\"></textarea>\r\n");
      out.write("		               </div>\r\n");
      out.write("		               <div style=\"display: inline-block; width: 100%;\">\r\n");
      out.write("		                 <div style=\"display: inline-block; width: 83%;\">\r\n");
      out.write("		                   <label for=\"checkSpoiler\">\r\n");
      out.write("		                    <i class=\"fa-solid fa-face-meh fa-2xl\" style=\"color: #cccccc;\"></i>\r\n");
      out.write("		                    <input type=\"checkbox\" id=\"checkSpoiler\" style=\"display: none;\" />\r\n");
      out.write("		                   </label>\r\n");
      out.write("		                  <span style=\"color: #666666;\">스포일러가 포함된 코멘트를 가려보세요.</span>\r\n");
      out.write("		                 </div>\r\n");
      out.write("		                 <div style=\"display: inline-block; width: 16%; text-align: right;\">\r\n");
      out.write("		                  <button type=\"button\" class=\"btn\" style=\"color: #ffffff; background-color: #ff0558;\">등록</button>\r\n");
      out.write("		                 </div>\r\n");
      out.write("		               </div>\r\n");
      out.write("		            </div>\r\n");
      out.write("		          </div>\r\n");
      out.write("		        </div>\r\n");
      out.write("		      </div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"Video\">\r\n");
      out.write("		\r\n");
      out.write("			<h4 style=\"margin: 30px 0 0 30px; font-weight: bolder; \">동영상</h4>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"img_8\">\r\n");
      out.write("		\r\n");
      out.write("			<h4 style=\"margin: 30px 0 0 30px; font-weight: bolder; \">사진</h4>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"carousel3D\">\r\n");
      out.write("				<figure id=\"spinner3D\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				    <img src=\"https://image.tmdb.org/t/p/w780/jbremGnsRR4XZMDj97YHt20isRP.jpg\">\r\n");
      out.write("				</figure>\r\n");
      out.write("			</div>\r\n");
      out.write("			<span style=\"float:left\" class=\"ss-icon\" onclick=\"galleryspin('-')\">&lt;</span>\r\n");
      out.write("			<span style=\"float:right\" class=\"ss-icon\" onclick=\"galleryspin('')\">&gt;</span>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
