/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.72
 * Generated at: 2023-05-10 07:41:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.InetAddress;

public final class common_005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/NCS/workspace(spring)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683599588119L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.InetAddress");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 String ctxPath = request.getContextPath(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	.header_width {\r\n");
      out.write("		width: 80px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		margin-left: 3px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.header_hover:hover {\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("		background-color: #E3F2FD;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 프로필 드롭다운 */\r\n");
      out.write("	.dropdown {\r\n");
      out.write("	  position: relative;\r\n");
      out.write("	  display: inline-block;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.dropdown-content {\r\n");
      out.write("	  display: none;\r\n");
      out.write("	  position: absolute;\r\n");
      out.write("	  background-color: #f9f9f9;\r\n");
      out.write("	  min-width: 100px;\r\n");
      out.write("	  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("	  z-index: 1;\r\n");
      out.write("	  border-radius: 10px; \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.dropdown-content a {\r\n");
      out.write("	  color: black;\r\n");
      out.write("	  padding: 12px 16px;\r\n");
      out.write("	  text-decoration: none;\r\n");
      out.write("	  display: block;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.dropdown-content a:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("	.dropdown:hover .dropdown-content {display: block;}\r\n");
      out.write("	\r\n");
      out.write("	.activeHeaderMenu {\r\n");
      out.write("		color: #086BDE !important;\r\n");
      out.write("		background-color: #E3F2FD;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.header_profile_css {\r\n");
      out.write("		border-radius: 50%; \r\n");
      out.write("		background-color: #E3F2FD; \r\n");
      out.write("		width:50px; \r\n");
      out.write("		height:50px; \r\n");
      out.write("		display: flex; \r\n");
      out.write("		justify-content: center; \r\n");
      out.write("		align-items: center;\r\n");
      out.write("		color:white;\r\n");
      out.write("		font-size: 25pt;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#msgStack {\r\n");
      out.write("		position: fixed;\r\n");
      out.write("		right: 16px;\r\n");
      out.write("		z-index: 1;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	a {\r\n");
      out.write("		color: black;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("// 소켓 전역변수 설정\r\n");
      out.write("var socket  = null;\r\n");
      out.write("\r\n");
      out.write("// toast생성 및 추가\r\n");
      out.write("function onMessage(evt){\r\n");
      out.write("	var data = evt.data;\r\n");
      out.write("	// toast\r\n");
      out.write("	let toast = \"<div class='toast' role='alert' aria-live='assertive' aria-atomic='true'>\";\r\n");
      out.write("	toast += \"<div class='toast-header'><i class='fas fa-bell mr-2'></i><strong class='mr-auto'>알림</strong>\";\r\n");
      out.write("	toast += \"<button type='button' class='ml-2 mb-1 close' data-dismiss='toast' aria-label='Close'>\";\r\n");
      out.write("	toast += \"<span aria-hidden='true'>&times;</span></button>\";\r\n");
      out.write("	toast += \"</div> <div class='toast-body'>\" + data + \"</div></div>\";\r\n");
      out.write("	$(\"#msgStack\").append(toast);   // msgStack div에 생성한 toast 추가\r\n");
      out.write("	$(\".toast\").toast({\"animation\": true, \"autohide\": false});\r\n");
      out.write("	$('.toast').toast('show');\r\n");
      out.write("};	\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	// 웹소켓 연결\r\n");
      out.write("	/* sock = new SockJS(\"/alert.on\");\r\n");
      out.write("	socket = sock;\r\n");
      out.write("\r\n");
      out.write("	// 소켓이 열렸을 때\r\n");
      out.write("	sock.onopen = function() {\r\n");
      out.write("	 	console.log('open');\r\n");
      out.write("	}; */\r\n");
      out.write("	const url = window.location.host; // 웹브라우저의 주소창의 포트까지 가져옴\r\n");
      out.write("    const pathname = window.location.pathname; // 최초 '/' 부터 오른쪽에 있는 모든 경로\r\n");
      out.write("    const appCtx = pathname.substring(0, pathname.lastIndexOf(\"/\") ); \r\n");
      out.write("    const root = url + appCtx;\r\n");
      out.write("	var ws = new WebSocket('ws://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.serverPort}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/alert.on');		   \r\n");
      out.write("       \r\n");
      out.write("    socket = ws;\r\n");
      out.write("    \r\n");
      out.write("	ws.onopen = function() {\r\n");
      out.write("   		console.log('Info: connection opened.');\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	ws.onmessage = function(event) {\r\n");
      out.write("   		console.log('Info: connection onmessage.');\r\n");
      out.write("\r\n");
      out.write("    	onMessage(event); // toast 생성\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	ws.onclose = function(event) {\r\n");
      out.write("   		console.log('Info: connection closed');\r\n");
      out.write("	};\r\n");
      out.write("    \r\n");
      out.write("	ws.onerror = function(err) {\r\n");
      out.write("   		console.log('Error:', err);\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write(" 	// 현재 메뉴 표시하기\r\n");
      out.write("	const pathName = window.location.pathname;\r\n");
      out.write("	const ctxPath = '");
      out.print(ctxPath);
      out.write("';\r\n");
      out.write("	let menuName = pathName.substring(ctxPath.length+1);\r\n");
      out.write("	\r\n");
      out.write("	const index = menuName.indexOf(\"/\");\r\n");
      out.write("	\r\n");
      out.write("	menuName = menuName.substring(0,index) || menuName.substring(0,menuName.length-3);\r\n");
      out.write("	$('div#'+menuName).addClass('activeHeaderMenu'); // 현재 메뉴에 색 입히기\r\n");
      out.write("	\r\n");
      out.write("	$(\"#header_profile_bg\").text(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\".substring(0,1));	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"msgStack\"></div>\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm\">\r\n");
      out.write("\r\n");
      out.write("  <ul class=\"navbar-nav headerNavbar\">\r\n");
      out.write("  	<li class=\"nav-item mt-1\">\r\n");
      out.write("      	<div style=\"padding: 0 0 0 10%; margin-right: 100px; cursor:pointer;\" class=\"nav-link\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/index.on\"'>\r\n");
      out.write("      		<img src='");
      out.print(ctxPath);
      out.write("/resources/images/sist_logo.png' width=\"150\"/>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav-item\"  >\r\n");
      out.write("    	<div id='index' class=\"nav-link text-dark header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/index.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-home fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">홈</div>\r\n");
      out.write("    	</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\" >\r\n");
      out.write("      	<div id='mail' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/mail/receiveMailBox.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-envelope fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">메일</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("    	<div id='organization' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/organization.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-sitemap fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">조직도</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='attend' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/attend/myAttend.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-business-time fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">근태관리</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='approval' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/approval/home.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-stamp fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">전자결재</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='manage' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/manage/info/viewInfo.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-id-card-alt fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">사원관리</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='schedule' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/schedule/schedule.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"far fa-calendar-alt fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">일정관리</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='reservation' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/reservation/meetingRoom.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-bookmark fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">자원예약</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='notice' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/notice/list.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-bullhorn fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">공지사항</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='community' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/community/list.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-chalkboard-teacher fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">커뮤니티</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='survey' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/survey/surveyList.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-chart-pie fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">설문조사</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("      	<div id='chat' class=\"nav-link text-dark  header_hover header_width\" onClick='location.href=\"");
      out.print(ctxPath);
      out.write("/chat.on\"'>\r\n");
      out.write("    		<div class=\"text-center\"><i class=\"fas fa-comments fa-lg\"></i></div>\r\n");
      out.write("    		<div style=\"text-align: center;\">채팅</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <li class=\"nav-item\" style=\"margin-left: 12%;\">\r\n");
      out.write("      	<div class=\"nav-link dropdown\" onClick='location.href=\"#\"'>\r\n");
      out.write("    		<div class=\"dropbtn\">\r\n");
      out.write("    			\r\n");
      out.write("    			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /WEB-INF/tiles/common_header.jsp(236,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.loginuser.empimg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<img style=\"border-radius: 50%; height:50px; width: 50px;\" src=\"");
            out.print(ctxPath );
            out.write("/resources/images/profile/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginuser.empimg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("								\r\n");
      out.write("   			</div>\r\n");
      out.write("   			<div class=\"dropdown-content\">\r\n");
      out.write("			    <a href=\"");
      out.print(ctxPath);
      out.write("/manage/info/viewInfo.on\">프로필</a>\r\n");
      out.write("			    <a href=\"");
      out.print( ctxPath);
      out.write("/login.on\">로그아웃</a>\r\n");
      out.write("			</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("    </li>\r\n");
      out.write("  \r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/tiles/common_header.jsp(232,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginuser.empimg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"header_profile_css\" id=\"header_profile_bg\"></div>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
